### ISSUE TITLE
TextGrids rounding too aggressively?

### ISSUE THREAD

**Issue by Kedersha** [prosodylab/Prosodylab-Aligner#22]
hi! I was aligning a bunch of files the other day to make stimuli for an experiment, and one of them ended with the word "curb". I truncated it to include the burst of the final "b", as well as a little silence afterwards, but the aligner generated a TextGrid that completely cut it out.  The wav file is the same length as it was when I truncated it, so when you view it without the TextGrid the final burst is very apparent.

Would it be worth considering having a limit on the generated TextGrids such that they're the same length as the soundfile?

**Comment by kylebgorman** [comment]
I forget what we figured out with this...should I close it for now? (we can always reopen if it crops up again)

**Comment by Kedersha** [comment]
Yeah, sounds good! I don't think it's super urgent now.
