### ISSUE TITLE
.scores.txt, .Align.mlf

### ISSUE THREAD

**Issue by mchlwgnr** [prosodylab/Prosodylab-Aligner#38]
- should be written to data directory insted of aligner directory
- it might be good to keep the .mlf after conversion to Textgrids, for troubleshooting purposes

**Comment by kylebgorman** [comment]
I'd like to specify the location of these with command-line options (otherwise they'd not be generated). Does that sound okay?

**Comment by mchlwgnr** [comment]
i think we should just generate them by default for the time being, or at
least the scores.txt file--it's just really useful to have at least the
scores.txt file available in case one needs it without having to realign.

**Comment by kylebgorman** [comment]
Question: would you prefer, all else held equal, to have both of these as hidden files always stashed in a secret location (the data directory), or to have users specify a (known) location for them? The latter seems better somewhat better to me.

They are equally easy for me to enable, so we should decide purely on the UX merits.

Kyle

**Comment by mchlwgnr** [comment]
ok, this might be just our local habits, but i liked it when they were just
hidden files that were always there. it's often at a late point in data
analysis when i want to look at scores to get some idea about the alignment
quality, at a point when i might not want to realign the data because we've
already run the scripts to add extra tiers etc. Since the file isn't big,
it doesn't really hurt to put it there, right? The mlf file is actually
only relevant for debugging, but but since it's also small i wouldn't mind
having it there, but here only saving it as an open set per flag would not
really affect the way we use the aligner.

**Comment by kylebgorman** [comment]
okay, we'll do the hidden file version.

**Comment by kylebgorman** [comment]
And, both of them are now back.

This will assist me in debugging the one remaining issue: pauses.
