### ISSUE TITLE
change order of operations in the install?

### ISSUE THREAD

**Issue by Kedersha** [prosodylab/Prosodylab-Aligner#39]
In the HTK install portion of the instructions, the following order is given:

$ make clean
$ export CPPFLAGS=-UPHNALG
$ ./configure --disable-hlmtools --disable-hslab
$ make -j4 all
$ sudo make -j4 install

However, make clean doesn't work if you don't run the configure first--could we switch the order to:

$ export CPPFLAGS=-UPHNALG
$ ./configure --disable-hlmtools --disable-hslab
$ make clean
$ make -j4 all
$ sudo make -j4 install

I didn't want to change it without checking, just in case I had this wrong!

**Comment by kylebgorman** [comment]
> On Feb 9, 2015, at 5:25 PM, Kedersha <notifications@github.com> wrote:
> 
> In the HTK install portion of the instructions, the following order is given:
> 
> $ make clean
> $ export CPPFLAGS=-UPHNALG
> $ ./configure --disable-hlmtools --disable-hslab
> $ make -j4 all
> $ sudo make -j4 install
> 
> However, make clean doesn't work if you don't run the configure first--could we switch the order to:
> 
> $ export CPPFLAGS=-UPHNALG
> $ ./configure --disable-hlmtools --disable-hslab
> $ make clean
> $ make -j4 all
> $ sudo make -j4 install


Oh, good point, that should be changed.

The only function of `make clean` is that if the person has previously tried to compile HTK and failed for some other reason, they have to `make clean` first (which deletes already-compiled bits). People starting from scratch have no particular reason to do that.

Kyle

**Comment by Kedersha** [comment]
Thanks! :) I've also been running into some trouble trying to run the newest version of the aligner, but I'll ask about it later. Are github issues or email a better way to get in touch?

**Comment by kylebgorman** [comment]
Issues are better. Use email if you need to send me data so I can reproduce the error.

K

**Comment by Kedersha** [comment]
Great, thanks
