### ISSUE TITLE
ERROR [+1452]  ReadDictProns: word out of order in dict

### ISSUE THREAD

**Issue by irfus** [prosodylab/Prosodylab-Aligner#48]
While trying to train the aligner model, I'm getting the error quoted in the title. I've attached a log of the traceback, as well as the dict and yaml config for the model training. I'm not sure what order the words in the dict are supposed to be in. Is the arrangement supposed to match the order of the phoneset in the config? 
Help appreciated. 
[log.txt](https://github.com/prosodylab/Prosodylab-Aligner/files/212976/log.txt)
[marathi_config_dict.zip](https://github.com/prosodylab/Prosodylab-Aligner/files/212971/marathi_config_dict.zip)

**Comment by kylebgorman** [comment]
Hi, have you tried just sorting the dictionary with sort.py? E.g.,

  ./sort.py < marathi.dict > marathi.dict.temp; mv marathi.dict.temp marathi.dict

It hasn't failed me yet; if that doesn't work, then we'll have to look at the HTK code to figure out what order it wants things to be in.

**Comment by irfus** [comment]
It worked, thanks!
