### ISSUE TITLE
Words with apostrophes not recognized

### ISSUE THREAD

**Issue by majure** [prosodylab/Prosodylab-Aligner#49]
Some of my .lab transcripts have words with apostrophes, and they are being placed in the OOV list despite being in the dictionary. For example, DON'T. Do the apostrophes need to be escaped in the transcript somehow? I can't find any documentation about this.

**Comment by kylebgorman** [comment]
Sometimes this indicates that the transcript has a "smart quote" in it, (https://en.wikipedia.org/wiki/Quotation_mark#Quotation_marks_in_English), whereas the dictionary has the ASCII quote character (decimal char 39).

But if that's not it, and you're sure, then please email me a minimal workable example and I'll be glad to debug tomorrow.

**Comment by majure** [comment]
That was it. Thank you.

**Comment by kylebgorman** [comment]
Glad it was something relatively simple ;)
