### ISSUE TITLE
Fatal error during installation (OS X)

### ISSUE THREAD

**Issue by seanstappas** [prosodylab/Prosodylab-Aligner#51]
After calling `make -j4 all` in the htk directory, the following error was thrown:

> strarr.c:21:10: fatal error: 'malloc.h' file not found

This was fixed for me by replacing `#include <malloc.h>`with `#include <malloc/malloc.h>` in htk/HTKLib/strarr.c. (OS X El Capitan 10.11.4 15E65)

**Comment by kylebgorman** [comment]
Thanks for that report. Let me suggest a more-general solution: replace any
import of malloc.h with stdlib.h. malloc.h is non-standard, but ANSI C
onward requires that malloc be defined in stdlib.h. (I'm looking at p. 252
of K&R, ANSI C edition.)

If you're interested, please report this issue upstream to the HTK folks.
(You may not be the first person complaining about it).

**Comment by seanstappas** [comment]
Hey, thanks for the quick reply. Replacing with stdlib.h did indeed do the trick as well. I will make sure to report it upstream.
