### ISSUE TITLE
Error installing HTK & Aligner 

### ISSUE THREAD

**Issue by ayushch3** [prosodylab/Prosodylab-Aligner#58]
I have tried everything to install HTK on my ubuntu 14.04 VM, for some reason, it doesn't seem to install correctly. This are the logs. 

(cd HTKTools && make all) \
          || case "" in *k*) fail=yes;; *) exit 1;; esac;
make[1]: Entering directory `/home/azureuser/task/htk/HTKTools'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/azureuser/task/htk/HTKTools'
(cd HLMTools && make all) \
          || case "" in *k*) fail=yes;; *) exit 1;; esac;
make[1]: Entering directory `/home/azureuser/task/htk/HLMTools'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/azureuser/task/htk/HLMTools'
azureuser@fuse-backend2:~/task/htk$ sudo make install
(cd HTKTools && make all) \
          || case "" in *k*) fail=yes;; *) exit 1;; esac;
make[1]: Entering directory `/home/azureuser/task/htk/HTKTools'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/azureuser/task/htk/HTKTools'
(cd HTKTools && make install) \
        || case "" in *k*) fail=yes;; *) exit 1;; esac;
make[1]: Entering directory `/home/azureuser/task/htk/HTKTools'
if [ ! -d /usr/local/bin ] ; then mkdir /usr/local/bin ; fi
for program in HSLab HBuild HCompV HCopy HDMan HERest HHEd HInit HLEd   HList HLRescore HLStats HMMIRest HParse HQuant HRest HResults HSGen HSmooth HVite  ; do /usr/bin/install -c -m 755 ${program} /usr/local/bin ; done
make[1]: Leaving directory `/home/azureuser/task/htk/HTKTools'
(cd HLMTools && make all) \
          || case "" in *k*) fail=yes;; *) exit 1;; esac;
make[1]: Entering directory `/home/azureuser/task/htk/HLMTools'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/azureuser/task/htk/HLMTools'
(cd HLMTools && make install) \
        || case "" in *k*) fail=yes;; *) exit 1;; esac;
make[1]: Entering directory `/home/azureuser/task/htk/HLMTools'
for program in Cluster HLMCopy LAdapt LBuild LFoF LGCopy LGList LGPrep LLink LMerge LNewMap LNorm LPlex LSubset  ; do /usr/bin/install -c -m 755 ${program} /usr/local/bin ; done
make[1]: Leaving directory `/home/azureuser/task/htk/HLMTools'

Once I clone the git and try to run the help command, I get this error:

  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "aligner/__init__.py", line 1, in <module>
    from .aligner import Aligner
  File "aligner/aligner.py", line 91
    <NUMSTATES> 5""", file=proto)
                          ^
SyntaxError: invalid syntax

I am out of ideas as to how to install HTK, nothing seems to work

**Comment by kylebgorman** [comment]
Looks like you've correctly installed HTK to me (what makes you think you've failed?)

When you try to launch the aligner, from Python, it fails because you're launching it with Python 2.7 and it's a Python 3 application. Install Python 3.4 or more recent and then use it to launch the aligner (try `python3` if nothing else works).

**Comment by kylebgorman** [comment]
Any news here? If not please close or let me know so I can.
