### ISSUE TITLE
getting an error in re.py

### ISSUE THREAD

**Issue by dcavar** [prosodylab/Prosodylab-Aligner#60]
Any idea, what might be causing this error?

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/Prosodylab_Aligner-2.0-py3.5.egg/aligner/__main__.py", line 92, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Prosodylab_Aligner-2.0-py3.5.egg/aligner/corpus.py", line 66, in __init__
  File "/usr/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

**Comment by kylebgorman** [comment]
This is weird because `main.py` doesn't exist in the aligner. It sounds
like you have a weird installation---can you try removing the package then
just reinstalling from GitHub in a clean directory?

**Comment by dcavar** [comment]
Well, we installed it from scratch on multiple systems, Win 10, Ubuntu 17.04, Mac OSX Sierra, using the git-distro, same issue. Three of us on four different machines. Maybe it is our data, maybe something in the transcription??? Shall I post the link to the data? It is the Chatino data from GORILLA on LINGUIST List, we just prepared it for Prosodylab/HTK.
Any help would be very much appreciated. :-) Thanks!

**Comment by mmcauliffe** [comment]
It showing up as 'main.py' is just because github parsing interprets the underscores, making it bold, line 92 of '\_\_main\_\_.py' is the initialization of a Corpus object.  Looking at https://github.com/prosodylab/Prosodylab-Aligner/blob/master/aligner/corpus.py#L66, phoneset doesn't have just strings in it, but I don't know why that would be the case.

**Comment by kylebgorman** [comment]
Yes, please send me something I can replicate (kylebgorman@gmail.com) and I
can take a look later today. Sorry you're having trouble.

**Comment by kylebgorman** [comment]
Any news? Let me know if I can close the issue.

**Comment by dcavar** [comment]
Hi Kyle,

Yes, it all worked. If I remember correctly, it was only about quoting. We got the aligner for Yiddish and Chatino.

Thanks!

Best wishes

DC


--
Damir Cavar
http://damir.cavar.me/


-----Original Message-----
