### ISSUE TITLE
how to used Prosodylab-Aligner on windows platform?

### ISSUE THREAD

**Issue by onsunsl** [prosodylab/Prosodylab-Aligner#61]
The document does not have other operating system on the use of instructions, whether to support windows or linux platform, if use of windows should be what kind of steps? thanks.

**Comment by kylebgorman** [comment]
If you are a developer it ought to be possible to get this working on Windows, but we do not support it---none of us even have a Windows machine.

Probably the easiest way to run this software "on Windows" is to just install Linux in a virtual machine and use it from there.

Closing this issue---but please feel free to submit a pull request with notes on how to install this software on Windows if you like.

**Comment by mmcauliffe** [comment]
You can also try the Montreal Forced Aligner, which has native executables built for Windows (https://montrealcorpustools.github.io/Montreal-Forced-Aligner/).
