### ISSUE TITLE
ERROR [+1232] cannot find word in dictionary

### ISSUE THREAD

**Issue by TaylorWJones** [prosodylab/Prosodylab-Aligner#63]
I am getting the following error:

  ERROR [+1232]  NumParts: Cannot find word 'ali in dictionary
 FATAL ERROR - Terminating program HLEd

I checked the obvious (\'ali is in the dictonary, and has the necessary backslash, capitalization is fine...). 
Any suggestions?

**Comment by kylebgorman** [comment]
The HTK backend (which is where that error is coming from) has a horrible
time with word-initial ASCII punctuation, but not in a way that is like,
documented, sigh.

Assuming the two strings are a perfect byte-for-byte match (no unicode
normalization issues, etc.), the best bet is to do without (or if this is
intended to be, say a glottal stop), sorry to say, or to escape it with \.

**Comment by TaylorWJones** [comment]
Thanks! I think I just sorted it out by just redoing the whole dictionary and transcripts. Now I'm on to a different error.
