### ISSUE TITLE
32-bit libraries for Linux installation

### ISSUE THREAD

**Issue by rgriscom** [prosodylab/Prosodylab-Aligner#82]
Just a note that some libraries are needed in addition to libc-dev for Linux installations: 
https://stackoverflow.com/questions/54082459/fatal-error-bits-libc-header-start-h-no-such-file-or-directory-while-compili

**Comment by kylebgorman** [comment]
Thanks, I added gcc-multilib to the list of dependencies for Ubuntu.

>
The X11 thing, I think, is a red herring because you can issue
`--disable-hlmtools --disable-hslab` when configuring, and you won't need
X11 headers (or at least that used to be true).
