### ISSUE TITLE
phoneset OY0 is not in hmmdefs,but it used in eng.dict

### ISSUE THREAD

**Issue by sybilWsybil** [prosodylab/Prosodylab-Aligner#84]
phoneset OY0 is not in hmmdefs,but it used in eng.dict。How can I get the information of OY0 in hmmdefs? Could you update hmmdefs for me?

**Comment by kylebgorman** [comment]
It’s automatically generated, so no. There was no OY0 in the source data.

You can train your own model (with the -t flag) if there are phonemes you
want to use but which are not part of the provided model.

K

**Comment by kylebgorman** [comment]
Closing issue; hopefully that's enough information.
